[build]
  command = "npm install --force && npm run build"
  environment = { NODE_OPTIONS = "--no-warnings", CI = "false" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-emails"
