export const HERE_APP_ID = 'kLeEsu9HMvL3pmKh2BrY';
export const HERE_API_KEY = 'kE8FGA1pUGnxn3IdbU2ukhWZjxFWIWd38p2lAy8d1jw';
export const EDGE_URL = "https://sxjdyfdpdhepsgzhzhak.supabase.co/functions/v1"
export const GOOGLE_MAPS_API_KEY = 'AIzaSyBsY7TWsifdD_oYfwhEKBqVdLzfBaSeuA';
export const EMAILJS_SERVICE_ID = 'service_2r0se76';
export const EMAILJS_API_KEY = 'qVS-rHwiDSnK_KcU9';
export const MAILCHIMP_API_KEY = '62187fe32cbe5dee78bde2adf5715dfb-us11';
export const MAILGUN_DOMAIN = 'sandbox47ce8785c831477abdac4337e652ee45.mailgun.org';
export const TOMTOM_API_KEY = 'gC8HgENnEmix00louuAFWGM1mjOg6Kb8'
export const states = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
  ]
  export const terms = [
    'Acl',
    'Ankylosing',
    'Copd',
    'Fibromyalgia',
    'Lupus',
    'Myelitis',
    'Spondylitis',
    'Adhd',
    'Aging',
    'Alopecia',
    'Alzheimer',
    'Anemia',
    'Arthritis',
    'Asthma',
    'Autism',
    'Autoimmune',
    'Bones',
    'Brain',
    'Cardiovascular',
    'Cell',
    'Cervical',
    'Chronic',
    'Colitis',
    "Crohn's",
    'Dementia',
    'Depression',
    'Diabetes',
    'Disc',
    'Disease',
    'Disorder',
    'Dysfunction',
    'Encephalitis',
    'Endocrine',
    'Erectile',
    'Failure',
    'Gastrointestinal',
    'Hair',
    'Head',
    'Hearing',
    'Heart',
    'Herniated',
    'Hypothyroid',
    'Inflammation',
    'Kidney',
    'Ligament',
    'Liver',
    'Loss',
    'Lupus',
    'Lumbar',
    'Meniscus',
    'Migraine',
    'Migraines',
    'Neurodegenerative',
    'Neurological',
    'Neuropathy',
    'Orthopedic',
    'Osteoarthritis',
    'Pain',
    'Palsy',
    'Parkinsons',
    'Peyronies',
    'Radiculopathy',
    'Rotator',
    'MS',
    'Multiple sclerosis',
    'Sickle',
    'Soft',
    'Spinal',
    'Spondylolisthesis',
    'Spondylosis',
    'Sprains',
    'Strains',
    'Stroke',
    'Tear',
    'Tendonitis',
    'Tinnitus',
    'Tissue',
  ];
  export const provinces = ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Northwest Territories', 'Nunavut', 'Yukon']
  export const countries =  ['United States', 'Canada', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Anguilla', 'Antigua &amp; Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia &amp; Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Chad', 'Chile', 'China', 'Colombia', 'Congo', 'Cook Islands', 'Costa Rica', 'Cote D Ivoire', 'Croatia', 'Cruise Ship', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Estonia', 'Ethiopia', 'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia', 'French West Indies', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Kyrgyz Republic', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Namibia', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Pierre &amp; Miquelon', 'Samoa', 'San Marino', 'Satellite', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'St Kitts &amp; Nevis', 'St Lucia', 'St Vincent', 'St. Lucia', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', "Timor L'Este", 'Togo', 'Tonga', 'Trinidad &amp; Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks &amp; Caicos', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Virgin Islands (US)', 'Yemen', 'Zambia', 'Zimbabwe']


export const mexicanStates = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Coahuila',
  'Colima',
  'Durango',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Mexico City',
  'Mexico State',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
];

